export const wingWords = ["laundry", "compose", "liberty", "freckle",
"premium", "laborer", "morning", "protest", "crystal", "railcar",
"silence", "emotion", "content", "purpose", "inquiry", "pottery",
"compact", "despair", "dentist", "traffic", "bathtub", "quarter",
"qualify", "capital", "recruit", "concept", "central", "perfume",
"dribble", "auction", "justice", "elegant", "concede", "inspire",
"prevent", "applaud", "percent", "article", "jealous", "wriggle",
"deprive", "suspect", "looting", "nursery", "quarrel", "version",
"realize", "kinship", "feature", "present", "designer", "hospital",
"abstract", "flatware", "document", "cemetery", "threaten", "district",
"business", "shortage", "appetite", "superior", "contempt", "magnetic",
"fragrant", "retailer", "syndrome", "momentum", "tendency", "dominant",
"training", "vigorous", "behavior", "mistreat", "birthday", "aquarium",
"displace", "skeleton", "magazine", "relative", "ancestor", "observer",
"language", "twilight", "congress", "activate", "separate", "profound",
"minister", "cucumber", "mourning", "decisive", "coverage", "affinity",
"tropical", "function", "theorist", "governor", "contrary"]